/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#2563EB",
          50: "#EBF2FF",
          100: "#D4E2FF",
          200: "#A9C5FF",
          300: "#7EA8FF",
          400: "#538BFF",
          500: "#2563EB",
          600: "#1A4ED4",
          700: "#1239B0",
          800: "#0B258C",
          900: "#051468",
          foreground: "#ffffff",
        },
        secondary: {
          DEFAULT: "#3B82F6",
          50: "#ECF4FF",
          100: "#D8E8FF",
          200: "#B1D0FF",
          300: "#8AB8FF",
          400: "#639FFF",
          500: "#3B82F6",
          600: "#2F6ADF",
          700: "#2352C8",
          800: "#173AAB",
          900: "#0B228E",
          foreground: "#000000",
        },
        accent: {
          DEFAULT: "#60A5FA",
          50: "#F0F8FF",
          100: "#E0F0FF",
          200: "#C0E0FF",
          300: "#A0D0FF",
          400: "#80C0FF",
          500: "#60A5FA",
          600: "#4D8CE6",
          700: "#3A73CC",
          800: "#2759B3",
          900: "#144099",
          foreground: "#000000",
        },
        highlight: {
          DEFAULT: "#00BFFF",
          50: "#E6F9FF",
          100: "#CCF3FF",
          200: "#99E6FF",
          300: "#66D9FF",
          400: "#33CCFF",
          500: "#00BFFF",
          600: "#0099CC",
          700: "#007399",
          800: "#004D66",
          900: "#002633",
          foreground: "#000000",
        },
        warning: {
          DEFAULT: "#EF4444",
          50: "#FEF2F2",
          100: "#FEE2E2",
          200: "#FECACA",
          300: "#FCA5A5",
          400: "#F87171",
          500: "#EF4444",
          600: "#DC2626",
          700: "#B91C1C",
          800: "#991B1B",
          900: "#7F1D1D",
          foreground: "#ffffff",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "slide-up": {
          "0%": { opacity: "0", transform: "translateY(30px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in-left": {
          "0%": { opacity: "0", transform: "translateX(-30px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "slide-in-right": {
          "0%": { opacity: "0", transform: "translateX(30px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "gradient-shift": {
          "0%, 100%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.8" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.6s ease-out",
        "slide-up": "slide-up 0.6s ease-out",
        "slide-in-left": "slide-in-left 0.8s ease-out",
        "slide-in-right": "slide-in-right 0.8s ease-out",
        "gradient-shift": "gradient-shift 3s ease-in-out infinite",
        float: "float 3s ease-in-out infinite",
        pulse: "pulse 2s ease-in-out infinite",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      boxShadow: {
        "glow-highlight": "0 0 20px rgba(0, 191, 255, 0.3)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
